In [1]:
import torch

In [2]:
torch.__version__

'2.8.0+cu126'

In [3]:
x = torch.tensor([1, 2, 3])
x[0,0]

IndexError: too many indices for tensor of dimension 1

In [4]:
x[0:0]

tensor([], dtype=torch.int64)

In [5]:
x

tensor([1, 2, 3])

In [6]:
x[0]

tensor(1)

In [7]:
x[0].item()

1

In [8]:
x.ndim

1

In [9]:
x.shape

torch.Size([3])

In [10]:
matrix = torch.rand(size=(3,4))

In [11]:
matrix.ndim

2

In [12]:
print(matrix)

tensor([[0.4866, 0.5324, 0.9236, 0.0605],
        [0.7931, 0.5337, 0.4423, 0.9232],
        [0.8725, 0.7461, 0.1970, 0.2664]])


In [13]:
print(matrix.dtype)

torch.float32


In [14]:
oness = torch.ones(size=(2,2))

In [22]:
import torch

cuda_available = torch.cuda.is_available()
print("CUDA available:", cuda_available)

device = torch.device("cuda" if cuda_available else "cpu")
print("Using device:", device)

if cuda_available:
    print("GPU count:", torch.cuda.device_count())
    print("Current device index:", torch.cuda.current_device())
    print("Device name:", torch.cuda.get_device_name(0))

CUDA available: False
Using device: cpu


In [21]:
ones2 = torch.ones(size=(2,3,3))

In [20]:
ones2


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])